/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms.HelpForm;

import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Eldridge
 */
public class TestProcessPanel extends javax.swing.JPanel {

    private int NumberOfProcessTabs = 0;
    //private int NumberOfSubProcessTabs = 1;
    private List<JTextField> ProcessNameList = new ArrayList<JTextField>();
    private List<JTextField> subProcessNameList = new ArrayList<JTextField>();
    /**
     * Creates new form ProcessPanelBackup1
     */
    public TestProcessPanel() {
        initComponents();
        /* add tab to add new tab when click */
        //subProcess.add(new JPanel(), "+", NumberOfProcessTabs++);
        //subProcess.addChangeListener(changeListener);
        Process.add(new ProcessPanel(), "Process 1", NumberOfProcessTabs++);
        Process.add(new JPanel(), "+", NumberOfProcessTabs++);
        Process.addChangeListener(changeListener);
    }
    
    ChangeListener changeListener = new ChangeListener() {
        @Override
        public void stateChanged(ChangeEvent e) {
            addNewTabProcess();
        }

    };
    
    private void addNewTabProcess() {
        
        int index = NumberOfProcessTabs - 1;
        if (Process.getSelectedIndex() == index) { /* if click new tab */
            /* add new tab */
            JPanel this_panel = new ProcessPanel();
            for (Component c : this_panel.getComponents()) {
                if (c instanceof JTextField) {
                    JTextField textField = ((JTextField)c);
                    String name, contact;
                    //if(textField.getName().startsWith("subProcess")) {
                        // Name field
                        this.ProcessNameList.add(textField);
                    //} else {
                        // Contact field
                    //    contact = textField.getText();
                    //}
       // Validate and persist.

                }
            }
            Process.add(this_panel, "Process " + String.valueOf(NumberOfProcessTabs),
                    index);
            /* set tab is custom tab */
            //jTabbedPane1.setTabComponentAt(index, new DemoCustomTab(this));
            Process.removeChangeListener(changeListener);
            Process.setSelectedIndex(index);
            Process.addChangeListener(changeListener);
            NumberOfProcessTabs++;
        }
    }
    /*
     private void addNewTabSubProcess() {
        int index = NumberOfSubProcessTabs - 1;
        if (subProcess.getSelectedIndex() == index) { // if click new tab 
            // add new tab 
            JPanel this_panel = new SubProcessPanel();
            for (Component c : this_panel.getComponents()) {
                if (c instanceof JTextField) {
                    JTextField textField = ((JTextField)c);
                    String name, contact;
                    //if(textField.getName().startsWith("subProcess")) {
                        // Name field
                        this.subProcessNameList.add(textField);
                    //} else {
                        // Contact field
                    //    contact = textField.getText();
                    //}
       // Validate and persist

                }
            }
            subProcess.add(this_panel, "Sub Process " + String.valueOf(NumberOfSubProcessTabs),
                    index);
            // set tab is custom tab
            //jTabbedPane1.setTabComponentAt(index, new DemoCustomTab(this));
            subProcess.removeChangeListener(changeListener);
            subProcess.setSelectedIndex(index);
            subProcess.addChangeListener(changeListener);
            NumberOfSubProcessTabs++;
        }
    }
*/

    /**
     * @return the ProcessName
     */
    public List<JTextField> getProcessName() {
        return ProcessNameList;
    }

    /**
     * @param ProcessName the ProcessName to set
     */
    public void setProcessName(List<JTextField> ProcessName) {
        this.ProcessNameList = ProcessName;
    }
     
    public void getData()
    {
        
    }
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Process = new javax.swing.JTabbedPane();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        Process.setBackground(new java.awt.Color(255, 255, 255));
        Process.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Process, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Process, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        Process.getAccessibleContext().setAccessibleName("Process 1");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Process;
    // End of variables declaration//GEN-END:variables
}
